## 2. Create a fly.toml file

Create this file in your project root:
```toml
app = "proyecto-back"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "3000"
```